[technote]
id = "SITCOMTN-124"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-124.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-124"
github_default_branch = "main"
date_created = 2024-04-03T17:14:00Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Peter S."
name.family = "Ferguson"
internal_id = "fergusonps"
orcid = "https://orcid.org/0000-0001-6957-1627"
[[technote.authors.affiliations]]
name = "Department of Physics"
internal_id = "WisconsinMadison"
address = "University of Wisconsin-Madison, Madison, WI 53706, USA"
[[technote.authors]]
name = {given = "Jeffrey L.", family = "Carlin"}
internal_id = "carlinjl"
orcid = "https://orcid.org/0000-0002-3936-9628"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
